---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lbrns
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
     labels:
      app: backend
    spec:
      containers:
      - image: cloudmanly/eks:blueapp 
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080     
---
apiVersion: v1
kind: Service
metadata:
  namespace: lbrns
  name: backend
  labels:
    app: backend
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: backend