---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lbrns
  name: blue
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 1
  template:
    metadata:
     labels:
        app: blue
    spec:
      containers:
      - image: cloudmanly/eks:blue
        imagePullPolicy: Always
        name: blue
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  namespace: lbrns
  name: blue
  labels:
    app: blue
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: blue

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lbrns
  name: green
spec:
  selector:
    matchLabels:
      app: green
  replicas: 1
  template:
    metadata:
     labels:
        app: green
    spec:
      containers:
      - image: cloudmanly/eks:green 
        imagePullPolicy: Always
        name: green
        ports:
        - containerPort: 8081
        
---
apiVersion: v1
kind: Service
metadata:
  namespace: lbrns
  name: green
  labels:
    app: green
spec:
  ports:
    - port: 8081
      protocol: TCP
  selector:
    app: green