apiVersion: v1
kind: Secret
metadata:
  name: top-secret
data:
  username: Ym9i
  password: c3VwZXItc2VjcmV0
---
kind: Pod
apiVersion: v1
metadata:
  name: blueapp
spec:
  volumes:
   - name: secret-vol
     secret:
        secretName: top-secret
  containers:
  - name: blueapp
    image: cloudmanly/eks:blueapp
    ports:
      - containerPort: 8080
    volumeMounts:
    - name: secret-vol
      readOnly: true
      mountPath: /opt/tomcat/secret-vol