---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bgrns
  name: blue
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 1
  template:
    metadata:
     labels:
        app: blue
    spec:
      containers:
      - image: cloudmanly/eks:blue 
        imagePullPolicy: Always
        name: blue
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  namespace: bgrns
  name: blue
  labels:
    app: blue
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: blue